### ISSUE TITLE
vocabulary GET to -.trellisldp.org and -.w3.org require SSL handshake 

### ISSUE THREAD

**Issue by christopher-johnson** [trellis-ldp-archive/trellis-vocabulary#1]
Ref: https://github.com/trellis-ldp/trellis-http/issues/3

AWS S3 redirects requests to http://www.trellisldp.org/ns/trellis.html# to a local datacenter host. 
https://fmu25t5z0d.execute-api.us-east-1.amazonaws.com/trellis

This is a debug log from the client during the test.
[trellistest-httpclient_debug.txt](https://github.com/trellis-ldp/trellis-vocabulary/files/1353936/trellistest-httpclient_debug.txt)

The datacenter domain cert can be fetched from https://fmu25t5z0d.execute-api.us-east-1.amazonaws.com/  

Some of the w3.org served namespaces, like OWL and XML redirect to https and some are served directly, like AS.  It is the same certificate for all of them.

**Comment by acoburn** [comment]
To be clear, is this causing failing tests?

**Comment by christopher-johnson** [comment]
for me locally, yes.  I suspect that this may be a consequence of my having implemented a modified keystore for my local JDK, however.  I assume that you do not have the same issue.  Nonetheless, I believe that tracking (and maintaining) certificates is relevant especially if one is implementing "trusted" resource dependencies from TLS domains.

**Comment by acoburn** [comment]
For this issue, I would argue that, given that it only applies to running the test suite, and if a user is already using a modified keystore, then it is that user's responsibility to add the relevant certs to their own local keystore defined in the system property `javax.net.ssl.keyStore`.
